name: Deploy website

on:
  push:
    branches: [main]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build backend
      run: |
        cd backend
        npm ci --force
        npm run build
        mv ./dist/ ../build

    - name: Build frontend
      run: |
        cd frontend
        npm ci
        npm run build
        mv ./dist/complaint/ ../build/frontend

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/

    - name: Restart website
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo 'ssh works'
          source /home/deviant/nodevenv/domains/complaint.${{ secrets.SSH_HOST }}/public_html/16/bin/activate
          cd /home/deviant/domains/complaint.${{ secrets.SSH_HOST }}/public_html
          pm2 reload complaint
